version: 1.0.{build}

image: Ubuntu2204

build_script:

- cmd: echo "AppVeyor"

test: off

#---------------------------------#

#  Skip builds for doc changes    #

#---------------------------------#

skip_commits:

  # Regex for matching commit message

  message: /\(doc\).*/

environment:
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCewxG+iJgKndgz2xKnkj2s1pRqmybUsaT2civDvvF5xz9t0Qm6QkRnFPP0/ipZP8VkLjPZA8U0yQ2XtArfdEF5aBJ85kLvQHLo8aiuqEicVxBhr5ZxjZMVDsFg0hRl5lDtK0ED/oWYVsrw9TwdHqIOElUfM6cKL7Qh3o4e9ADcOC5pEI+Yd+r4OA2Rjc3D+TJZJpomSIqi47PynEBG/267t15l06IzZUcLOMOmW7GitvVqJs/0pOxRt1IiGhVDTiK/haE1riWPnocAmfueH97xaVg2jItno4DnVNCD0ZWPcKJMp/A8A3Yz6bnYGRtXZ2PsGFPg73B8jFyCYa/+40CzutoqESYJdOUavsWIq0hGV609znjlsCgF6qVwx/SnnPyUpH2mbijfT5D6aRZSVtQ6ZBxIHhhLBEmU6NohRdvTvRmT14xeEkpZKdSj+M/DBeTurFNGYTDt7+GuBGi06F5NjGuG9Jj4ytlAx4EB2578hSxNYoQOgHGMXDXLN8fVSqUaYrdJnLi3Ue92C/7DEMHopA3athyxPBZml9jhw/8cmAAH9gmpV7kRU8KS74c22Q3wUQ9CjWWNaPGKRLDbe9zPFJKX2fa7NF2hHEH9rE1gZ+hahxrgRqhEAbDYSi6f17K8pzT6wFd+EU3xmNxLpxe7tbhDKCs+uYktfRW2Gf+kww== youremail@example.com

on_finish:
  - sh: export APPVEYOR_SSH_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
